version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_pass
      - MYSQL_DATABASE=tyapollo_database
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - mysqldata:/var/lib/mysql
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
    command: "yarn dev"
    depends_on:
      - db
volumes:
  mysqldata: